name: Start MacOS
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    name: MacOS Build
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Run the MacOS Environment
      run: source mac.sh
    - name: Show IP
      run: curl ifconfig.me
    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
